title: Wallpaper Reactor
description: Reactive & cross-platform live wallpapers.
theme: just-the-docs
color_scheme: dark

url: https://likeich.github.io/

# aux_links:
#   Releases: /releases/

ga_tracking: "G-YYB483JREW"
